# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'face.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nface.proto\x12\x0f\x66\x61\x63\x65recognition\"\"\n\x11\x45ncodeFaceRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"&\n\x12\x45ncodeFaceResponse\x12\x10\n\x08\x65ncoding\x18\x01 \x03(\x02\x32h\n\x0f\x46\x61\x63\x65Recognition\x12U\n\nEncodeFace\x12\".facerecognition.EncodeFaceRequest\x1a#.facerecognition.EncodeFaceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCODEFACEREQUEST']._serialized_start=31
  _globals['_ENCODEFACEREQUEST']._serialized_end=65
  _globals['_ENCODEFACERESPONSE']._serialized_start=67
  _globals['_ENCODEFACERESPONSE']._serialized_end=105
  _globals['_FACERECOGNITION']._serialized_start=107
  _globals['_FACERECOGNITION']._serialized_end=211
# @@protoc_insertion_point(module_scope)
